from __future__ import annotations

import subprocess
from pathlib import Path

import pytest


def git(cwd: Path, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(["git", *args], cwd=cwd, check=True, text=True, capture_output=True)


@pytest.fixture(autouse=True)
def isolated_environment(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    monkeypatch.setenv("MARPME_DISABLE_UPDATE_CHECK", "1")
    monkeypatch.setenv("MARPME_CACHE_DIR", str(tmp_path / "cache"))
    monkeypatch.setenv("GIT_AUTHOR_NAME", "Marpme Tests")
    monkeypatch.setenv("GIT_AUTHOR_EMAIL", "marpme@example.invalid")
    monkeypatch.setenv("GIT_COMMITTER_NAME", "Marpme Tests")
    monkeypatch.setenv("GIT_COMMITTER_EMAIL", "marpme@example.invalid")
    monkeypatch.delenv("MARPME_EPHEMERAL", raising=False)


@pytest.fixture
def repository(tmp_path: Path) -> Path:
    path = tmp_path / "project"
    path.mkdir()
    git(path, "init", "-q")
    (path / "README.md").write_text("# Project\n", encoding="utf-8")
    git(path, "add", "README.md")
    git(path, "commit", "-qm", "initial")
    return path


@pytest.fixture
def template_repository(tmp_path: Path) -> Path:
    path = tmp_path / "template"
    path.mkdir()
    git(path, "init", "-q")
    (path / "copier.yml").write_text(
        "_subdirectory: template\ndeck_name:\n  type: str\n  default: slidedeck\n",
        encoding="utf-8",
    )
    (path / "CHANGELOG.md").write_text(
        "# Changelog\n\n## 1.0.0 - 2026-08-26\n\n- Initial template.\n",
        encoding="utf-8",
    )
    template = path / "template"
    template.mkdir()
    (template / ".marpme" / "copier-answers.yml.jinja").parent.mkdir(parents=True)
    (template / ".marpme" / "copier-answers.yml.jinja").write_text(
        "# Generated by Copier; changes will be overwritten.\n"
        "{{ _copier_answers|to_nice_yaml -}}\n",
        encoding="utf-8",
    )
    (template / ".marpme" / "theme").mkdir(parents=True)
    (template / ".marpme" / "theme" / "company.css").write_text(
        "/* template v1 */\n", encoding="utf-8"
    )
    (template / ".marpme" / "skills" / "slides").mkdir(parents=True)
    (template / ".marpme" / "skills" / "slides" / "SKILL.md").write_text(
        "# Slide guidance\n", encoding="utf-8"
    )
    (template / ".marpme" / "starter" / "assets").mkdir(parents=True)
    (template / ".marpme" / "starter" / "deck.md").write_text(
        "---\nmarp: true\ntheme: company\n---\n\n# New presentation\n",
        encoding="utf-8",
    )
    (template / ".marpme" / "starter" / "custom.css").write_text(
        "/* deck styles */\n", encoding="utf-8"
    )
    git(path, "add", ".")
    git(path, "commit", "-qm", "template v1")
    git(path, "tag", "v1.0.0")
    return path


@pytest.fixture
def in_repository(monkeypatch: pytest.MonkeyPatch, repository: Path) -> Path:
    monkeypatch.chdir(repository)
    return repository
